#!/usr/bin/python3.8
import matplotlib.pyplot as plt

#################################
# Ethereum Price Analysis Program
#################################


plt.plot([1, 5, 10, 15], [1, 2, 3, 4])
plt.ylabel('some numbers')
plt.show()



